
openapi: 3.0.4
info:
  title: Promedic El Gran CH - API de Productos
  description: Esta es una API para gestionar el inventario de productos en la droguería Promedic El Gran CH.
  termsOfService: http://promedic.com/terms/
  contact:
    email: soporte@promedic.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Encuentra más sobre Promedic
  url: https://promedic.com
servers:
  - url: http://192.168.1.37/react_native_promedic/BacKend/
tags:
  - name: Producto
    description: Operaciones sobre productos

paths:
  /login.php:
    post:
      tags:
        - Producto
      summary: Iniciar sesión
      description: Inicia sesión con las credenciales del usuario.
      operationId: login
      requestBody:
        description: Credenciales de inicio de sesión
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "usuario@promedic.com"
                password:
                  type: string
                  example: "contraseña123"
        required: true
      responses:
        '200':
          description: Inicio de sesión exitoso
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: "jwt_token"
        '401':
          description: Credenciales inválidas
        '400':
          description: Error en la solicitud

  /listar_productos.php:
    get:
      tags:
        - Producto
      summary: Obtener todos los productos
      description: Devuelve una lista de todos los productos en el inventario.
      operationId: getProducts
      responses:
        '200':
          description: Lista de productos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Producto'
        '500':
          description: Error interno del servidor

  /agrega.php:
    post:
      tags:
        - Producto
      summary: Agregar un nuevo producto
      description: Agrega un nuevo producto al inventario.
      operationId: addProduct
      requestBody:
        description: Datos del producto a agregar
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Producto'
        required: true
      responses:
        '201':
          description: Producto agregado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Producto'
        '400':
          description: Entrada inválida

  /actualiza.php:
    put:
      tags:
        - Producto
      summary: Actualizar un producto
      description: Actualiza un producto existente en el inventario.
      operationId: updateProduct
      parameters:
        - name: id
          in: query
          description: ID del producto a actualizar
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        description: Datos del producto actualizado
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Producto'
        required: true
      responses:
        '200':
          description: Producto actualizado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Producto'
        '400':
          description: Entrada inválida
        '404':
          description: Producto no encontrado

  /get_datos.php:
    get:
      tags:
        - Producto
      summary: Obtener datos iniciales
      description: Obtiene datos necesarios como categorías y clasificaciones.
      operationId: getDatosIniciales
      responses:
        '200':
          description: Datos iniciales obtenidos exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  categorias:
                    type: array
                    items:
                      type: string
                      example: "Medicamentos"
                  clasificaciones:
                    type: array
                    items:
                      type: string
                      example: "A"
        '500':
          description: Error interno del servidor

components:
  schemas:
    Producto:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        nombre_producto:
          type: string
          example: "Paracetamol"
        descripcion_producto:
          type: string
          example: "Analgésico y antipirético"
        costo_adquisicion:
          type: number
          format: float
          example: 10.50
        codigo_barras:
          type: integer
          example: 123456789
        peso:
          type: string
          example: "500g"
        precio:
          type: number
          format: float
          example: 12.00
        cantidad_stock:
          type: integer
          example: 100
        id_clasificacion:
          type: integer
          example: 1
        id_categoria:
          type: integer
          example: 2
        id_estado_producto:
          type: integer
          example: 1
        id_marca:
          type: integer
          example: 3
        id_proveedor:
          type: integer
          example: 4
        fecha_vencimiento:
          type: string
          format: date
          example: "2025-12-31"
        cantidad_minima:
          type: integer
          example: 10
        cantidad_maxima:
          type: integer
          example: 200
    Error:
      type: object
      properties:
        code:
          type: integer
          example: 400
        message:
          type: string
          example: "Entrada inválida"
